### ISSUE TITLE
Update auf Elm 0.17

### ISSUE THREAD

**Issue by jvoigtlaender** [Shaomada/Elm-Project#1]
Intuitiv denke ich, dass es besser wäre, zunächst das Programm auf Elm-Version 0.17 zu heben, dann über Erweiterungen nachzudenken. Insbesondere bzgl. an- und abschaltbarer Subscriptions wird es so vermutlich architektonisch sauberer bzw. einfacher als erst im Nachgang darauf umzuschwenken.

**Comment by Shaomada** [comment]
Habe ich so gemacht.
Die Idee wäre natürlich auch sonst nicht gewesen, einen Leveleditor auf Elm 0.16 zu programmieren, sondern eventuell erst nur den Leveleditor in Elm 0.17 umzusetzen und danach den Rest des Codes zu heben.

**Comment by jvoigtlaender** [comment]
Ein Hinweis: Ihr `toCmd` ist ja recht hacky. Ich weise einfach mal auf meinen Kommentar zu analogem Aspekt bei einem anderen Studierenden hin: https://github.com/Sulring/elmaction/issues/8.

Mindestens wäre `Cmd.Extra.message` auch hier sicher die bessere Wahl (statt willkürlich `Random` ins Spiel zu bringen). Und vermutlich wäre darüber hinaus an den meisten Stellen statt Aufruf von `toCmd` oder `message` direktes rekursives Aufrufen der entsprechenden `update`-Funktion sinnvoll, ggfs. unter Verwendung von Helfern aus http://package.elm-lang.org/packages/ccapndave/elm-update-extra.

**Comment by Shaomada** [comment]
danke, ich war gerade dabei, eine Mail zu schreiben um zu fragen durch was man toCmd sinnvoll ersetzen könnte ^^

**Comment by jvoigtlaender** [comment]
Siehe übrigens auch: http://elm-community.github.io/elm-faq/17.html#how-do-i-generate-a-new-message-as-a-command
